THEMES = {
    "corporate_blue": {
        "key": "corporate_blue",
        "name": "Corporate Blue",
        "primary": "#1d4ed8",
        "secondary": "#0f172a",
        "accent": "#38bdf8",
        "background": "#f1f5f9",
        "surface": "#ffffff",
        "text": "#0f172a",
        "muted": "#475569",
        "border": "#e2e8f0",
        "success": "#15803d",
        "warning": "#b45309",
        "danger": "#b91c1c",
        "info": "#0369a1",
        "radius": "12px",
        "font": "Source Sans 3, Segoe UI, sans-serif",
        "heading": "Fraunces, Georgia, serif",
    },
    "modern_purple": {
        "key": "modern_purple",
        "name": "Modern Purple",
        "primary": "#7c3aed",
        "secondary": "#1e1b4b",
        "accent": "#c084fc",
        "background": "#f5f3ff",
        "surface": "#ffffff",
        "text": "#1e1b4b",
        "muted": "#5b21b6",
        "border": "#ddd6fe",
        "success": "#15803d",
        "warning": "#b45309",
        "danger": "#be123c",
        "info": "#6d28d9",
        "radius": "16px",
        "font": "Source Sans 3, Segoe UI, sans-serif",
        "heading": "Fraunces, Georgia, serif",
    },
    "emerald": {
        "key": "emerald",
        "name": "Emerald",
        "primary": "#047857",
        "secondary": "#064e3b",
        "accent": "#34d399",
        "background": "#ecfdf5",
        "surface": "#ffffff",
        "text": "#064e3b",
        "muted": "#065f46",
        "border": "#a7f3d0",
        "success": "#166534",
        "warning": "#b45309",
        "danger": "#b91c1c",
        "info": "#0f766e",
        "radius": "12px",
        "font": "Source Sans 3, Segoe UI, sans-serif",
        "heading": "Fraunces, Georgia, serif",
    },
    "dark_enterprise": {
        "key": "dark_enterprise",
        "name": "Dark Enterprise",
        "primary": "#60a5fa",
        "secondary": "#020617",
        "accent": "#22d3ee",
        "background": "#0b1220",
        "surface": "#111827",
        "text": "#e5e7eb",
        "muted": "#94a3b8",
        "border": "#1f2937",
        "success": "#4ade80",
        "warning": "#fbbf24",
        "danger": "#f87171",
        "info": "#38bdf8",
        "radius": "12px",
        "font": "Source Sans 3, Segoe UI, sans-serif",
        "heading": "Fraunces, Georgia, serif",
    },
    "minimal": {
        "key": "minimal",
        "name": "Minimal",
        "primary": "#111827",
        "secondary": "#111827",
        "accent": "#6b7280",
        "background": "#ffffff",
        "surface": "#f9fafb",
        "text": "#111827",
        "muted": "#6b7280",
        "border": "#e5e7eb",
        "success": "#15803d",
        "warning": "#b45309",
        "danger": "#b91c1c",
        "info": "#1d4ed8",
        "radius": "8px",
        "font": "Source Sans 3, Segoe UI, sans-serif",
        "heading": "Source Sans 3, Segoe UI, sans-serif",
    },
}

DEFAULT_MODULES = [
    "dashboard",
    "employees",
    "recruitment",
    "attendance",
    "leave",
    "payroll",
    "chatbot",
]


def serialize_org(org) -> dict:
    theme = THEMES.get(org.theme_key) or THEMES["corporate_blue"]
    return {
        "id": org.id,
        "name": org.name,
        "slug": org.slug,
        "status": org.status,
        "theme_key": org.theme_key,
        "layout_key": org.layout_key,
        "logo_url": org.logo_url,
        "modules": org.modules or DEFAULT_MODULES,
        "theme": theme,
    }
